name: Testing Laravel with PostgreSQL

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  php-cs-fixer:
    timeout-minutes: 10

    name: Apply PHP CS Fixer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: github.ref != 'refs/heads/main'
        uses: actions/checkout@v2
        with:
          ref: "${{ github.head_ref }}"
      - name: Cache .php-cs-fixer.cache
        uses: actions/cache@v2
        with:
          path: ./.php-cs-fixer.cache
          key: php-cs-cache
      - name: Run php-cs-fixer
        if: github.ref != 'refs/heads/main'
        uses: docker://oskarstark/php-cs-fixer-ga
      - name: Commit changes back to branch
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply php-cs-fixer changes"
          branch: "${{ github.head_ref }}"

  laravel-tests:
    timeout-minutes: 15

    name: Laravel (PHP ${{ matrix.php-versions }})

    needs:
      - php-cs-fixer

    env:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: database
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres
      SCOUT_DRIVER: meilisearch

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      meilisearch:
        image: getmeili/meilisearch
        ports:
          - 7700:7700

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.1', '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: swoole, pgsql
          tools: phpunit
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
      - name: Clear Laravel configuration
        run: php artisan config:clear
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
      - name: Run migrations
        run: php artisan migrate -v
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          MEILISEARCH_HOST: http://127.0.0.1:7700
        run: |
          php artisan migrate
          php artisan db:seed
          vendor/bin/pest
